version: '3'

services:
  golang:
    build:
      context: .
      dockerfile: ./build/package/golang/Dockerfile
    container_name: money_record_golang
    volumes:
      - ./:/go/src/money-record-api
    environment:
      - TZ=Asia/Tokyo
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    platform: linux/amd64
    image: mysql:5.7.38
    container_name: money_record_mysql
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: local_password
      MYSQL_ROOT_PASSWORD: local_password
      TZ: 'Asia/Tokyo'
    volumes:
      - money-record-db-data:/var/lib/mysql
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci

volumes:
  money-record-db-data:
